In [1]:
import re
import json
import os
from pprint import pprint
import networkx as nx
from matplotlib import pyplot as plt
import pygraphviz as pgv
import numpy as np

In [2]:
testdict={'0':{
    'a':{
        'aa':{},
        'ab':{
            'aba':{},
            'abb':{
                'abba':{},
                'abbb':{}
            },
            'abc':{}
        },
        'ac':{
            
        }
    },
    'b':{
        'ba':{
            'baa':{
                
            },
            'bab':{}
        },
        'bb':{}
    }
}}

In [3]:
def md_to_dict(text,n=0):
    try:
        maxh=max([x.count('#') for x in text.split('\n') if '-' not in x])
    except:
        pass
    try:
        minh=min([x.count('#') for x in text.split('\n') if x.count('#')!=0 and '-' not in x])
    except:
        minh=-1
    if(n==0):
        title=[x for x in text.split('\n') if '# ' in x][0]
        mindmap={}
        mindmap[title]=md_to_dict(text.replace(text[text.find(title):text.find(title)+len(title)+1],'').strip(),n+1)
        return mindmap
    elif(text!='' and n <=100):
        if('\n#' in text):
            mindmap={}
            for branch in text.split('\n'+'#'*minh):
                mindmap['#'*minh+branch.split('\n')[0].replace('#','')]=md_to_dict('\n'.join(branch.split('\n')[1:])[:-1],n+1)
            return mindmap
        else:
            l=min([x.find('-') for x in text.split('\n')])
            mindmap={}
            for branch in text.split('\n'+' '*l+'-'):
                key=branch.split('\n')[0].strip()
                if(key[0]=='-'):
                    key=key.replace('-','').strip()
                mindmap[key]=md_to_dict('\n'.join(branch.split('\n')[1:])[:-1],n+1)
            return mindmap
    else:
        return {}

In [4]:
file='Historia.md'
with open(file,'r') as f:
    text=f.read()
dic=md_to_dict('\n'.join([x for x in text.split('\n') if x!='']))
print()

In [5]:
with open(file[:-3]+'.json','w') as f:
    json.dump(dic,f)
os.system('json_to_freemind Historia.json Historia.mm')

32512

In [6]:
def gen_graph(pkey,node,graph):
    for key, item in node.items():
        if type(item) is dict:
            key=key.replace('\\','')
            graph.add_edge(pkey,key)
            gen_graph(key,item,graph)
        else:
            print(':',key)

In [20]:
maing=nx.Graph()
gen_graph('# Historia',dic['# Historia'],maing)
pos = nx.drawing.nx_agraph.graphviz_layout(maing, prog="dot", root=0)
arr=np.array([[0,-1],[1,0]])
for key, kpos in pos.items():
    pos[key]=[x[0] for x in arr.dot(np.array([[kpos[0]],[kpos[1]]]))]
    
nx.draw(maing, pos,
        node_color='blue',
        with_labels=True,
        alpha=0.5,
        node_size=1000,
       font_size=10)
plt.draw()
plt.show()

In [8]:
amaing=nx.nx_agraph.to_agraph(maing)

In [9]:
amaing.layout()
import time 
time.sleep(5)
amaing.draw('test.png')

/home/sergio/.local/lib/python3.8/site-packages/pygraphviz/agraph.py:1367: RuntimeWarning: Error: node # Historia, position 532.65,452.01, expected two doubles
Error: node ## La Restauració, position 617.11,518.71, expected two doubles
Error: node ## El catalanisme polític(1833-1931), position 463.28,408.86, expected two doubles
Error: node ## La Segona República (1931-1936), position 444.08,468.3, expected two doubles
Error: node ## La guerra civil, position 539.88,418.76, expected two doubles
Error: node ## El franquisme (1939-1975), position 557.56,339.09, expected two doubles
Error: node ## La transició i la democràcia (1975-1986), position 465.42,505.17, expected two doubles
Error: node **18751931**, position 625.03,483.16, expected two doubles
Error: node ### Primera etapa:, position 723.58,566.22, expected two doubles
Error: node ### Segona etapa(1902-1931), position 562.86,585.99, expected two doubles
Error: node Inicis del catalanisme, position 412.15,398, expected two doubles

In [12]:
print(maing['# Historia'])

{'## La Restauració': {}, '## El catalanisme polític(1833-1931)': {}, '## La Segona República (1931-1936)': {}, '## La guerra civil': {}, '## El franquisme (1939-1975)': {}, '## La transició i la democràcia (1975-1986)': {}}


In [46]:
testg=nx.Graph()
gen_graph('0',testdict['0'],testg)
testpos = nx.drawing.nx_agraph.graphviz_layout(testg, prog="dot", root=1)
for key, kpos in testpos.items():
    print(key,kpos,arr.dot(np.array([[kpos[0]],[kpos[1]]])))
    testpos[key]=[x[0] for x in arr.dot(np.array([[kpos[0]],[kpos[1]]]))]
nx.draw(testg, testpos,
        node_color='blue',
        with_labels=True,
        alpha=0.5,
        node_size=100)
plt.draw()
plt.show()

0 (171.0, 306.0) [[-306.]
 [ 171.]]
a (135.0, 234.0) [[-234.]
 [ 135.]]
aa (27.0, 162.0) [[-162.]
 [  27.]]
ab (99.0, 162.0) [[-162.]
 [  99.]]
aba (27.0, 90.0) [[-90.]
 [ 27.]]
abb (99.0, 90.0) [[-90.]
 [ 99.]]
abba (62.0, 18.0) [[-18.]
 [ 62.]]
abbb (135.0, 18.0) [[-18.]
 [135.]]
abc (171.0, 90.0) [[-90.]
 [171.]]
ac (171.0, 162.0) [[-162.]
 [ 171.]]
b (243.0, 234.0) [[-234.]
 [ 243.]]
ba (243.0, 162.0) [[-162.]
 [ 243.]]
baa (243.0, 90.0) [[-90.]
 [243.]]
bab (315.0, 90.0) [[-90.]
 [315.]]
bb (315.0, 162.0) [[-162.]
 [ 315.]]


In [10]:
pprint(pos)

{' cabal =  producció': (9452.9, 306.0),
 '# Historia': (21777.0, 810.0),
 '## El catalanisme polític(1833-1931)': (17654.0, 738.0),
 '## El franquisme (1939-1975)': (24591.0, 738.0),
 '## La Restauració': (12283.0, 738.0),
 '## La Segona República (1931-1936)': (20955.0, 738.0),
 '## La guerra civil': (22364.0, 738.0),
 '## La transició i la democràcia (1975-1986)': (30979.0, 738.0),
 '### 1ª etapa (19361975)': (24591.0, 666.0),
 '### 1ª etapa (19751982): La construcció de la democràcia': (30979.0, 666.0),
 '### 2ª etapa (1959-1975)': (28345.0, 666.0),
 '### 2ª etapa (1982-1986): La consolidació de la democràcia': (32584.0, 666.0),
 '### Bienni reformista:': (19969.0, 666.0),
 '### El bienni conservador': (20955.0, 666.0),
 '### Febrer-juliol 1936': (21494.0, 666.0),
 '### Govern provisional': (19563.0, 666.0),
 '### Primera etapa:': (10892.0, 666.0),
 '### Segona etapa(1902-1931)': (14061.0, 666.0),
 '#### Constitució 1876': (6064.9, 594.0),
 '#### Desastre de Cub': (12199.0, 594.0),

In [20]:
arr.shape

(2, 2)

In [35]:
arr.dot([[1], [3]])

array([[-3],
       [ 1]])

In [22]:
pprint(arr)

array([[ 0, -1],
       [ 1,  0]])


In [ ]:
np.matrix

In [32]:
np.array([kpos])

array([[171., 306.]])

In [34]:
np.array([kpos])*arr

array([[   0., -306.],
       [ 171.,    0.]])

In [40]:
arr.dot(np.array([[kpos[0]],[kpos[1]]]))

array([[-306.],
       [ 171.]])

In [45]:
pprint(pos)

{' cabal =  producció': [-306.0, 9452.9],
 '# Historia': [-810.0, 21777.0],
 '## El catalanisme polític(1833-1931)': [-738.0, 17654.0],
 '## El franquisme (1939-1975)': [-738.0, 24591.0],
 '## La Restauració': [-738.0, 12283.0],
 '## La Segona República (1931-1936)': [-738.0, 20955.0],
 '## La guerra civil': [-738.0, 22364.0],
 '## La transició i la democràcia (1975-1986)': [-738.0, 30979.0],
 '### 1ª etapa (19361975)': [-666.0, 24591.0],
 '### 1ª etapa (19751982): La construcció de la democràcia': [-666.0, 30979.0],
 '### 2ª etapa (1959-1975)': [-666.0, 28345.0],
 '### 2ª etapa (1982-1986): La consolidació de la democràcia': [-666.0,
                                                                32584.0],
 '### Bienni reformista:': [-666.0, 19969.0],
 '### El bienni conservador': [-666.0, 20955.0],
 '### Febrer-juliol 1936': [-666.0, 21494.0],
 '### Govern provisional': [-666.0, 19563.0],
 '### Primera etapa:': [-666.0, 10892.0],
 '### Segona etapa(1902-1931)': [-666.0, 14061.0],
 '#

In [16]:
def sep_y(dic):
    none=False
    n=0
    while not none:
        none=True
        if(n%100==0):
            print(n)
        for key,pos in dic.items():
            for k,kp in dic.items():
                if(k!=key and pos[1]-kp[1]<300 and pos[1]-kp[1]>0):
                    dic[key][1]+=50
                    none=False
                    break
                elif(k!=key and pos[1]-kp[1]>-300 and pos[1]-kp[1]<0):
                    dic[k][1]+=50
                    none=False
                    break
        n=n+1

In [21]:
sep_ymul(pos)

In [22]:
nx.draw(maing, pos,
        node_color='blue',
        with_labels=True,
        alpha=0.5,
        node_size=1000,
       font_size=10)
plt.draw()
plt.show()

In [19]:
def sep_ymul(dic):
    for key,pos in dic.items():
        dic[key][1]*=5